export const articlesMock = {
    "articles": [
        {   
            id: "1",
            title: 'Un titulo lorem ipsum',
            drophead: 'Un subtitulo lorem ipsum mas largo',
            author: 'Autor deconocido',
            date: new Date(),
            image1: '',
            introduction: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nisl nisl aliquet nisl, nec a',
            body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nisl nisl aliquet nisl, nec a',
        },
        {   
            id: "2",
            title: 'Un titulo lorem ipsum',
            drophead: 'Un subtitulo lorem ipsum mas largo',
            author: 'Autor deconocido',
            date: new Date(),
            image1: '',
            introduction: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nisl nisl aliquet nisl, nec a',
            body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nisl nisl aliquet nisl, nec a',
        },
        {
            id: "3",
            title: 'Un titulo lorem ipsum',
            drophead: 'Un subtitulo lorem ipsum mas largo',
            author: 'Autor deconocido',
            date: new Date(),
            image1: '',
            introduction: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nisl nisl aliquet nisl, nec a',
            body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nisl nisl aliquet nisl, nec a',
        },
        {
            id: "4",
            title: 'Un titulo lorem ipsum',
            drophead: 'Un subtitulo lorem ipsum mas largo',
            author: 'Autor deconocido',
            date: new Date(),
            image1: '',
            introduction: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nisl nisl aliquet nisl, nec a',
            body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nisl nisl aliquet nisl, nec a',
        },
        {   
            id: "5",
            title: 'Un titulo lorem ipsum',
            drophead: 'Un subtitulo lorem ipsum mas largo',
            author: 'Autor deconocido',
            date: new Date(),
            image1: '',
            introduction: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nisl nisl aliquet nisl, nec a',
            body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget aliquam ultricies, nisl nisl aliquet nisl, nec a',
        },
    ]
}